name: Java CI with Gradle

on:
  push:
    branches: [ "2004scape" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build -x test

    - run: rm clientscript-compiler/build/libs/neptune-clientscript-compiler-*-sources.jar
    - run: mv clientscript-compiler/build/libs/neptune-clientscript-compiler-*.jar clientscript-compiler/build/libs/RuneScriptCompiler.jar
    - run: sha256sum clientscript-compiler/build/libs/RuneScriptCompiler.jar | cut -d ' ' -f 1 | tr -d '\n' > clientscript-compiler/build/libs/RuneScriptCompiler.jar.sha256

    - name: Upload to GitHub
      uses: actions/upload-artifact@v3.1.0
      with:
        name: rt4-client
        path: clientscript-compiler/build/libs/*

    - name: Upload to Discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: clientscript-compiler/build/libs/RuneScriptCompiler.jar
