name: Build with Gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@v4

    - run: |
        ./gradlew build
        rm serverscript-compiler/build/libs/neptune-serverscript-compiler-*-sources.jar
        mv serverscript-compiler/build/libs/neptune-serverscript-compiler-*.jar serverscript-compiler/build/libs/RuneScriptCompiler.jar
        sha256sum serverscript-compiler/build/libs/RuneScriptCompiler.jar | cut -d ' ' -f 1 | tr -d '\n' > serverscript-compiler/build/libs/RuneScriptCompiler.jar.sha256

    - uses: actions/upload-artifact@v4
      with:
        name: jar
        path: serverscript-compiler/build/libs/*
